[package]
name = "idek_lyon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
idek = { path = "../engine" }
lyon = "0.17.10"